In [1]:
import pandas as pd 
import numpy as np 
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt 
%matplotlib inline
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv(r'F:\AI\LibrariesForAI\Supervised Learning\Simple linear regression\homeprices.csv')

In [3]:
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
x_df=df.drop(['price'],axis=1)

In [5]:
y_df=df['price']

In [6]:
lr=LinearRegression()

In [7]:
lr.fit(x_df,y_df)

LinearRegression()

In [8]:
lr.coef_

array([135.78767123])

In [9]:
lr.intercept_

180616.43835616432

Pickle File

In [10]:
import pickle

In [11]:
with open('lr_model','wb') as file:
    pickle.dump(lr,file)

In [12]:
with open('lr_model','rb') as file:
     mp=pickle.load(file)

In [13]:
mp.coef_

array([135.78767123])

### Create a file named sample.json with some data

In [14]:
import json

In [15]:
sampleJson ={
    'name' : 'Luminar',
    'place' : 'Kochi',
    'phone' : '7897894561'
}

In [16]:
json_object=json.dumps(sampleJson)

In [17]:
json_object

'{"name": "Luminar", "place": "Kochi", "phone": "7897894561"}'

In [18]:
with open('sample.json','w') as file:
    file.write(json_object)

In [19]:
with open('sample.json','r') as file:
    newdata=json.load(file)

In [20]:
newdata

{'name': 'Luminar', 'place': 'Kochi', 'phone': '7897894561'}

Save Trained Model using joblib

In [21]:
import joblib

In [22]:
joblib.dump(lr,'model_joblib_new')

['model_joblib_new']

In [24]:
mj=joblib.load('model_joblib_new')

In [25]:
mj.coef_

array([135.78767123])

In [26]:
mj.intercept_

180616.43835616432

In [27]:
joblib.load('lr_model')

LinearRegression()