In [1]:
# Install python package - Numpy

In [2]:
# pip install numpy
# import numpy
# We use import numpy as np, where (as np) is alias name, which is alternating name for numpy. 

In [1]:
import numpy as np

In [4]:
myList=[1,2,3,4,5]

In [5]:
print(myList)

[1, 2, 3, 4, 5]


In [6]:
myList

[1, 2, 3, 4, 5]

In [7]:
type(myList)

list

In [8]:
# dir(np)

In [9]:
# help(np)

In [10]:
arr=np.array(myList)

In [11]:
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [13]:
# Shape of the array
arr.shape

(5,)

In [14]:
arr.size

5

In [17]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

ar1=np.array([my_lst1,my_lst2,my_lst3])  # Since, we give more than 1 arguments inside array(), we need to give inside [].

In [18]:
type(ar1)

numpy.ndarray

In [19]:
ar1.shape

(3, 5)

In [20]:
ar1.size

15

In [21]:
ar1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [22]:
# Numpy array indexing

myLst1=[1,2,3,4,5]
arr=np.array(myLst1)

In [23]:
print(arr[0])

1


In [24]:
print(arr[1])

2


In [25]:
print("The third element is",arr[2])
print("The fourth element is",arr[3])

The third element is 3
The fourth element is 4


In [28]:
# Access 2D array

my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

ar1=np.array([my_lst1,my_lst2,my_lst3])

In [29]:
ar1[0,2]  # For both raw and coloumn, indexing starts with 0.

3

In [30]:
ar1[0,1]

2

In [31]:
# Second raw, fifth coloumn

ar1[1,4]

6

In [33]:
valArr=np.array([[1,2,3],[4,5,6]])
print(valArr)
print(valArr.shape)
print(valArr.size)
print(valArr[0,0])
print(valArr[1,2])

[[1 2 3]
 [4 5 6]]
(2, 3)
6
1
6


In [4]:
# Create a 5*5 array

newArr=np.array([[1,2,3,4,5],[6,7,8,9,10],[1,2,3,4,5],[11,12,13,14,15],[20,25,30,35,40]])
print(newArr)
print(newArr.shape)
print(newArr.size)
print(newArr[2,1])
print(newArr[3,0])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [11 12 13 14 15]
 [20 25 30 35 40]]
(5, 5)
25
2
11


In [5]:
# Neagative Indexing

valArr=np.array([[1,2,3],[4,5,6]])
print(valArr)

[[1 2 3]
 [4 5 6]]


In [11]:
print(valArr[1,-1])

6


In [3]:
# Numpy Array slicing

lst=[1,2,3,4,5,6,7,8,9,10]
arr=np.array(lst)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
print(arr[0:5])
arr[3:]
arr[0:5]

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [11]:
arr[-3:-1]

array([8, 9])

In [6]:
# Step

arr[::2]
arr[1::3]

array([2, 5, 8])

In [8]:
# Slicing 2D array

my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

ar1=np.array([my_lst1,my_lst2,my_lst3])

print(ar1)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [15]:
ar1[1:,:]
ar1[:,1:]

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [7, 6, 8, 9]])

In [16]:
# Arange function

np.arange(10)  # 10 elements needed in dummy array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(10,20) # Range given for elements needed

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(10,20,2) # Step function can be used with arange

array([10, 12, 14, 16, 18])

In [19]:
# Linspace

np.linspace(0,100)   # For creating an array from 0 to 100, which follows normal distribution

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [ ]:
# Numpy Data types

# Prefer Note book

In [4]:
# Defining data type

arr=np.array([1,2,3,4,5],dtype='S')         # data type forcefully changed to string, initially dtype will be none.
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [5]:
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [6]:
arr=np.array([1,2,3,4,5],dtype=np.int64)   # Forcefully converting dtype to integers,as eventhough its integers it may be read as strings in excel, so it needs to be converted to integers for mathmatical operations.
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


In [10]:
# Array Math

x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x,"\n")
print(y)

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]]


In [11]:
x+y

array([[ 6,  8],
       [10, 12]])

In [12]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [13]:
x-y

array([[-4, -4],
       [-4, -4]])

In [14]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [15]:
x*y

array([[ 5, 12],
       [21, 32]])

In [16]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [17]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [18]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [20]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [21]:
np.exp(x)  # Exponential, Eg: e raise to 1, like that.

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [22]:
np.log(x)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [23]:
np.cos(x)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [24]:
np.tan(x)

array([[ 1.55740772, -2.18503986],
       [-0.14254654,  1.15782128]])

In [25]:
# Floor, ceil, round

x=np.array([[1.5,2.5],[3.1,4.9]])
np.floor(x)

array([[1., 2.],
       [3., 4.]])

In [26]:
np.ceil(x)  # Will go to next value

array([[2., 3.],
       [4., 5.]])

In [27]:
np.round(x)  # Will go next of above .5 values, and will keep base if less than or equal to .5

array([[2., 2.],
       [3., 5.]])

In [28]:
x.dot(y)   # dot product

array([[25. , 29. ],
       [49.8, 57.8]])

In [29]:
np.dot(x,y)

array([[25. , 29. ],
       [49.8, 57.8]])

In [30]:
np.sum(x)

12.0

In [33]:
np.sum(x,axis=1)   # Axis=0/1  0---> column  1---> row

array([4., 8.])

In [34]:
np.sum(x,axis=0)

array([4.6, 7.4])

In [35]:
x.T   # Transpouse function

array([[1.5, 3.1],
       [2.5, 4.9]])

In [2]:
# Numpy Array copy vs view

arr=np.array([1,2,3,4,5])
x=arr     # For viewing

In [3]:
arr[0]=100

In [4]:
print(arr)
print(x)

[100   2   3   4   5]
[100   2   3   4   5]


In [6]:
arr=np.array([1,2,3,4,5])
x=arr.copy()     # For copying

In [7]:
arr[0]=100
print(arr)

[100   2   3   4   5]


In [8]:
print(x)

[1 2 3 4 5]


In [10]:
# Numpy Array Reshaping

arr=np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
ar1=arr.reshape(4,3)
ar1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
# Flattening the arrays
# 2D ---> 1D

ar1.reshape(-1)        # Mostly used in neural network

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
np.arange(1,7).reshape(3,2).sum(axis=0) # We can do operations with . ,like this.

array([ 9, 12])

In [16]:
# Iterating Arrays

arr=np.arange(1,7).reshape(3,2)
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
for x in arr:
    print(x)

[1 2]
[3 4]
[5 6]


In [18]:
# Joining Numpy arrays

ar1=np.array([1,2,3])
ar2=np.array([4,5,6])

In [20]:
np.concatenate((ar1,ar2))

array([1, 2, 3, 4, 5, 6])

In [26]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1)
print(arr2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [23]:
np.concatenate((arr1,arr2))  # BY default, it will concatinate with axis=0(colunm wise)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [24]:
np.concatenate((arr1,arr2),axis=1)  # Row wise concatination

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])